categorias_arbitros = ['FEB',
                        'A1',
                        'A2',
                        'A3',
                        'A4',
                        'PROVINCIAL 1',
                        'PROVINCIAL 2',
                        'PROVINCIAL 3',
                        'ESCUELA']

categorias_oficiales = ['ACB',
                        'LIGA FEM Y LEB PLATA',
                        'LIGA FEM  2 Y EBA',
                        '1  DIVISION',
                        'PROVINCIAL 1',
                        'PROVINCIAL 2',
                        'NUEVOS']

categorias_feb = ['LIGA ACB', 'LEB PLATA', 'LIGA FEMENINA', 'LIGA FEMENINA 2', 'LIGA EBA', '1ª DIVISIÓN NACIONAL BSR']

categorias_federados = ['1ª NACIONAL MASCULINA A1',
                       '1ª NACIONAL FEMENINA A1',
                       '1ª NACIONAL MASCULINA A2',
                       '1ª NACIONAL FEMENINA A2',
                       '2ª ARAGONESA MASCULINA',
                       '2ª ARAGONESA FEMENINA',
                       '3ª ARAGONESA MASCULINA',
                       '3ª ARAGONESA FEMENINA',
                       'SOCIAL MASCULINO ORO',
                       'SOCIAL MASCULINA PLATA',
                       'SOCIAL MASCULINA BRONCE',
                       'JUNIOR ARAGON MASCULINO 1ª',
                       'JUNIOR ARAGON FEMENINO 1ª',
                       'JUNIOR ARAGON MASCULINO 2ª',
                       'JUNIOR ARAGON FEMENINO 2ª',
                       'JUNIOR ARAGON MASCULINO 3ª',
                       'JUNIOR ARAGON FEMENINO 3ª',
                       'COPA SOCIAL ORO',
                       'Cº ARAGON JUNIOR MASCULINO 1ª',
                       'Cº ARAGON JUNIOR FEMENINO 1ª']

categorias_escolares = ['Cº ARAGON CADETE MASCULINO',
                       'Cº ARAGON CADETE FEMENINO',
                       'CADETE ARAGON MASCULINO',
                       'CADETE ARAGON FEMENINO',
                       'CADETE MASCULINO NIVEL B',
                       'CADETE FEMENINO NIVEL B',
                       'CADETE MASCULINO NIVEL C',
                       'CADETE FEMENINO NIVEL C',
                       'INFANTIL MASCULINO NIVEL A',
                       'INFANTIL FEMENINO NIVEL A',
                       'INFANTIL MASCULINO NIVEL B',
                       'INFANTIL FEMENINO NIVEL B',
                       'INFANTIL MASCULINO NIVEL C',
                       'INFANTIL FEMENINO NIVEL C',
                       'INTANTIL MIXTO',
                       'PREINFANTIL MASCULINO NIVEL A',
                       'PREINFANTIL MASCULINO NIVEL B',
                       'PREINFANTIL MASCULINO NIVEL C',
                       'PREINFANTIL FEMENINO NIVEL A',
                       'PREINFANTIL FEMENINO NIVEL B',
                       'PREINFANTIL FEMENINO NIVEL C', 
                       'ALEVIN MASCULINO NIVEL A',
                       'ALEVIN MASCULINO NIVEL B',
                       'ALEVIN MASCULINO NIVEL C',
                       'ALEVIN FEMENINO NIVEL A',
                       'ALEVIN FEMENINO NIVEL B',
                       'ALEVIN FEMENINO NIVEL C',
                       'ALEVIN MIXTO NIVEL B',
                       'ALEVIN MIXTO NIVEL C',
                       'BENJAMIN MASCULINO NIVEL A',
                       'BENJAMIN MASCULINO NIVEL B',
                       'BENJAMIN MASCULINO NIVEL C',
                       'BENJAMIN FEMENINO NIVEL A',
                       'BENJAMIN FEMENINO NIVEL B',
                       'BENJAMIN FEMENINO NIVEL C',
                       'BENJAMIN MIXTO']

campos_desplazamientos = ['PAB. PUEBLA ALFINDEN',
                          'PAB. LA MUELA',
                          'PAB. ZUERA',
                          'PAB. CUARTE HUERVA',
                          'PALACIO UTEBO',
                          'COL. ANFORA-CUARTE',
                          'PAB. EJEA',
                          'PAB. CALATAYUD',
                          'PAB. ANFORA',
                          'PAB. ALCAÑIZ',
                          'PAB. MALLEN',
                          'POL. PEDROLA',
                          'PAB. GURREA',
                          'POL. FIGUERUELAS',
                          'PAB. EPILA',
                          'PAB. GALLUR',
                          'PAB. JUAN LANUZA-UTEBO',
                          'POL. LA ALMUNIA', 
                          'PEÑAS CENTER',
                          'PAB. EL PARQUE', 
                          'POL. ANDORRA', 
                          'PAB. FUENTES EBRO', 
                          'PAB. J. LANUZA-UTEBO',
                          'PAB. VILLAMAYOR',
                          'PAB. TARAZONA',
                          'LA ISLA',
                          'PAB. GELSA',
                          'PAB. ALAGON',
                          'P. MULTIUSOS ZUERA',
                          'ASOCIACIACION VILLANUA',
                          'PAB. LAS FUENTES-UTEBO',
                          'PAB. CADRETE',
                          'PAB. MONTAÑANA']          
          